{
 "title": "Rockset Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ws", "label": "Workspace", "query": "label_values(workspace_name)" }
  ]
 },
 "panels": [
  {
   "title": "Leaf CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rockset_leaf_cpu_utilization_percentage"
    }
   ]
  },
  {
   "title": "Leaf Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rockset_leaf_memory_utilization_percentage"
    }
   ]
  },
  {
   "title": "Aggregator CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rockset_agg_cpu_utilization_percentage"
    }
   ]
  },
  {
   "title": "Aggregator CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rockset_agg_memory_utilization_percentage"
    }
   ]
  },
  {
   "title": "Total Collection Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rockset_collection_size_bytes)",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Top 5 Largest Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, rockset_collection_size_bytes)",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  { "title": "Virtual Instance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Leaf CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rockset_leaf_cpu_utilization_percentage",
     "legendFormat": "virtual instance {{virtual_instance_id}}"
    }
   ]
  },
  {
   "title": "Leaf Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rockset_leaf_memory_utilization_percentage",
     "legendFormat": "virtual instance {{virtual_instance_id}}"
    }
   ]
  },
  {
   "title": "Aggregator CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rockset_agg_cpu_utilization_percentage",
     "legendFormat": "virtual instance {{virtual_instance_id}}"
    }
   ]
  },
  {
   "title": "Aggregator Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rockset_agg_memory_utilization_percentage",
     "legendFormat": "virtual instance {{virtual_instance_id}}"
    }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Query Executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rockset_queries[$__rate_interval])",
     "legendFormat": "virtual instance {{virtual_instance_id}}"
    }
   ]
  },
  {
   "title": "Query Executions by Query Lambda",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rockset_query_lambda_queries{workspace_name=~\"$ws\"}[$__rate_interval])",
     "legendFormat": "{{workspace_name}}.{{query_lambda}}/{{tag}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rockset_query_latency_seconds_bucket[10m])) by (le, tag, query_lambda, workspace_name))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rockset_query_latency_seconds_bucket[10m])) by (le, tag, query_lambda, workspace_name))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Query Latency by Query Lambda [P95]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rockset_query_lambda_latency_seconds_bucket{workspace_name=~\"$ws\"}[$__rate_interval])) by (le, tag, query_lambda, workspace_name))",
     "legendFormat": "{{workspace_name}}.{{query_lambda}}/{{tag}}"
    }
   ]
  },
  {
   "title": "Query Errors by Error Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rockset_query_errors{error_code=~\"4.*\"}[$__rate_interval])",
     "legendFormat": "{{error_code}}"
    },
    {
     "expr": "increase(rockset_query_errors{error_code=~\"5.*\"}[$__rate_interval])",
     "legendFormat": "{{error_code}}"
    }
   ]
  },
  {
   "title": "Query Lambda Errors by Error Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rockset_query_lambda_errors[$__rate_interval])",
     "legendFormat": "{{workspace_name}}.{{query_lambda}}:{{error_code}}"
    }
   ]
  },
  { "title": "Collection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rockset_collection_documents{workspace_name=~\"$ws\"}",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Document Parse Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rockset_collection_parse_errors{workspace_name=~\"$ws\"}[$__rate_interval])",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Collection Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rockset_collection_size_bytes{workspace_name=~\"$ws\"}",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Total Ingest",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(rockset_collection_total_ingest_bytes{workspace_name=~\"$ws\"}[10m])",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Data Discovery Latency",
   "type": "graph",
   "description": "Latency from the time new data is added to a data source and the time it is first discovered by Rockset.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(rockset_collection_data_discovery_latency_bucket{workspace_name=~\"$ws\"}[10m])) by (le, workspace_name, collection_name))",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Data Process Latency",
   "type": "graph",
   "description": "Latency from first discovery of new data by Rockset to the time it is indexed and queryable.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(rockset_collection_data_process_latency_bucket{workspace_name=~\"$ws\"}[10m])) by (le, workspace_name, collection_name))",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  }
 ]
}